---

- name: Bootstrap cluster hosts for k3s installation
  hosts: rpi
  become: true
  roles:
    - k3s-bootstrap

- name: Install k3s server
  hosts: kubemaster
  become: true
  roles:
    - k3s-server

- name: Install k3s agents
  hosts: kubeworker
  become: true
  roles:
    - k3s-agent
