---

- name: Bootstrap cluster hosts for k3s installation
  hosts: rpi 
  become: yes
  vars:
    ip_address_netmask: "{{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.netmask }}"
  roles:
    - k3s-bootstrap

- name: Install k3s server
  hosts: kubemaster
  become: yes
  roles:
    - k3s-server

- name: Install k3s agents
  hosts: kubeworker
  become: yes
  roles:
    - k3s-agent
