---

- name: Prepare Raspberry Pi Cluster nodes with CentOS 7 for Kubernetes installation
  hosts: rpi
  connection: local
  #become: yes
  tasks:
    - fail:
    - name: Expand root partition
      command: /usr/bin/rootfs-expand

    - name: Activate Memory cgroup
      lineinfile:
        path: /tmp/cmdline.txt
        regexp: '(^\S.*(?<!cgroup_enable=memory)$)'
        line: '\1 cgroup_enable=memory'
        backrefs: yes

    - name: Update all packages
      yum:
        name: '*'
        state: latest
        
    - name: Reboot Hosts
      reboot:
