---

- name: Prepare localhost
  hosts: localhost
  connection: local
  tasks:
    - name: Install sshpass, this is required for Ansible ssh connection via password
      yum:
        name: sshpass
        state: present
    - name: Ensure public key for current User exists
      stat:
        path: ~/.ssh/id_rsa.pub

- name: Prepare Raspberry Pi Cluster nodes with CentOS 7 for Kubernetes installation
  hosts: rpi
  vars:
    ansible_user: root
    ansible_password: centos
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Assert if root partition needs to get expanded
      command: "growpart {{ ansible_cmdline.root | regex_replace('^(\/dev\/)(?P<device>.*)(p)(?P<devicenumber>.)$', '/dev/\\g<device> \\g<devicenumber>') }} -N"
      failed_when: false
      changed_when: false
      register: partition_needs_resizing
    
    - name: Expand root partition
      command: /usr/bin/rootfs-expand
      register: rootfs_expand_status
      failed_when: "'CHANGED' not in rootfs_expand_status.stdout"
      when: "'NOCHANGE' not in partition_needs_resizing.stdout"
    
    - name: Activate Memory cgroup
      lineinfile:
        path: /boot/cmdline.txt
        regexp: '(^\S.*(?<!cgroup_enable=memory)$)'
        line: '\1 cgroup_enable=memory'
        backrefs: yes

    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Assert if host needs rebooting
      command: needs-restarting -r
      failed_when: false
      changed_when: false
      register: reboot_required
    
    - name: Reboot Hosts
      reboot:
      when: "'Reboot is required' in reboot_required.stdout"

    - name: Create User for further Ansible automation
      user:
        name: "ansible"
        comment: "User for Ansible automation tasks"

    - name: Enable sudo permissions for Ansible user
      copy:
        content: "ansible ALL=(ALL) NOPASSWD:ALL"
        dest: /etc/sudoers.d/ansible
        validate: /usr/sbin/visudo -cf %s

    - name: Add public key of current User to authorized_keys of ansible User 
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
