---

- name: Copy service file for k3s server
  ansible.builtin.template:
    src: k3s.service.j2
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: 0755

- name: Enable and start K3s service
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: started
    enabled: true

- name: Wait for node-token
  ansible.builtin.wait_for:
    path: /var/lib/rancher/k3s/server/node-token

- name: Create directory .kube
  ansible.builtin.file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"

- name: Copy config file to user home directory
  ansible.builtin.copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~{{ ansible_user }}/.kube/config
    remote_src: true
    force: false
    owner: "{{ ansible_user }}"

- name: Replace localhost with IP of k3s server in kube config
  ansible.builtin.replace:
    path: ~{{ ansible_user }}/.kube/config
    regexp: "^(?P<parameter>.*)(?P<address>127\\.0\\.0\\.1)(?P<port>.*)$"
    replace: "\\g<parameter>{{ hostvars[groups['kubemaster'][0]].ansible_host }}\\g<port>"

- name: Set environment variable for kube config
  ansible.builtin.lineinfile:
    line: "export KUBECONFIG=.kube/config"
    dest: ~{{ ansible_user }}/.bash_profile

- name: Create kubectl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/kubectl
    state: link

- name: Create crictl symlink
  ansible.builtin.file:
    src: /usr/local/bin/k3s
    dest: /usr/local/bin/crictl
    state: link
