---

- name: Run kubeadm to initialize Kubernetes cluster
  ansible.builtin.command:
    cmd: "kubeadm init --pod-network-cidr 10.244.0.0/16 --apiserver-advertise-address={{ hostvars[inventory_hostname].ansible_host }}"
    creates: /var/lib/kubelet/config.yaml

# Necessary to use kubectl command
- name: Set Kubeconfig environment variable globally
  ansible.builtin.copy:
    src: kubeconfig.sh
    dest: /etc/profile.d/kubeconfig.sh

- name: Ensure .kube directory exists
  ansible.builtin.file:
    path: ~/.kube
    state: directory

- name: Symlink the kubectl admin.conf to ~/.kube/conf
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    force: true
    state: link

- name: Install EPEL release
  ansible.builtin.yum:
    name: epel-release
    state: present

- name: Install Python package manager
  ansible.builtin.yum:
    name:
      - python-pip
      - python-openshift
    state: present

- name: Upgrade pip
  community.general.pip:
    name: pip
    state: latest

- name: Install needed python packages for k8s module
  community.general.pip:
    name:
      - pyyaml
    state: present

- name: Get Kubernetes version for Weave installation
  ansible.builtin.shell: kubectl version | base64 | tr -d '\n'
  changed_when: false
  register: kubectl_version

- name: Check if Weave is already installed
  community.kubernetes.k8s_info:
    api_version: v1
    kind: DaemonSet
    name: weave-net
    namespace: kube-system
  register: weave_daemonset

- name: Configure Weave networking.
  ansible.builtin.command:
    cmd: "kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version={{ kubectl_version.stdout_lines[0] }}"
  register: weave_result
  changed_when: "'created' in weave_result.stdout"
  when: weave_daemonset.resources | length == 0

- name: Apply pod network plugin
  ansible.builtin.command:
    cmd: "kubectl apply -f https://cloud.weave.works/k8s/net?k8s-version={{ kubectl_version.stdout_lines[0] }} --kubeconfig /etc/kubernetes/admin.conf"
  when: weave_daemonset.resources | length == 0
